Repository gsantner/markor, pull requests merged in 2022-12, with the labels that each got.

#1928 Zim: use correct numbered list regex for view mode (closes #1729)
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextTextConverter.java
Labels: bug

#1914 Open file location from search dialog
  app/src/main/java/net/gsantner/markor/activity/MainActivity.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchResultSelectorDialog.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserFragment.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  app/thirdparty/java/other/writeily/model/WrMarkorSingleton.java
Labels: feature

#1930 Zim: Fix NPE for non-resolvable relative links with unreachable notebook dir (closes #1882) + Add compatibility support for anchor links
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextLinkResolver.java
  app/src/test/java/net/gsantner/markor/format/wikitext/WikitextLinkResolverTests.java
Labels: bug, enhancement

#1937 Fixes and tweaks
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/activity/DocumentShareIntoFragment.java
  app/src/main/java/net/gsantner/markor/activity/MainActivity.java
  app/src/main/java/net/gsantner/markor/activity/openeditor/OpenEditorFromShortcutOrWidgetActivity.java
  app/src/main/java/net/gsantner/markor/activity/openeditor/OpenFromShortcutOrWidgetActivity.java
  app/src/main/java/net/gsantner/markor/activity/openeditor/OpenShareIntoActivity.java
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/markor/format/asciidoc/AsciidocSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchResultSelectorDialog.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/markor/model/Document.java
  app/src/main/java/net/gsantner/markor/util/MarkorContextUtils.java
  app/src/main/java/net/gsantner/markor/util/ShortcutUtils.java
  app/src/main/java/net/gsantner/opoc/format/GsTextUtils.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
  app/src/main/res/values/string-not_translatable.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences_master.xml
  app/thirdparty/java/other/writeily/model/WrMarkorSingleton.java
  app/thirdparty/java/other/writeily/widget/WrFilesWidgetFactory.java
  app/thirdparty/java/other/writeily/widget/WrMarkorWidgetProvider.java
  app/thirdparty/res/layout/widget_file_item.xml
  app/thirdparty/res/xml/markor_widget.xml
Labels: enhancement

#1942 Add new Zim checkbox state "left arrow"
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextReplacePatternGenerator.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextTextConverter.java
  app/src/test/java/net/gsantner/markor/format/wikitext/WikitextReplacePatternGeneratorTests.java
  app/src/test/java/net/gsantner/markor/format/wikitext/WikitextSyntaxHighlighterTests.java
Labels: enhancement
