Repository gsantner/markor, pull requests merged in 2023-10, with the labels that each got.

#2118 Editor/viewer: Side margin improvements, closes #2111
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/res/values/dimens.xml
Labels: enhancement

#2107 Format: Add Orgmode SyntaxHighlight basic support
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/activity/SettingsActivity.java
  app/src/main/java/net/gsantner/markor/format/FormatRegistry.java
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeActionButtons.java
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeTextConverter.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/markor/model/Document.java
  app/src/main/res/menu/document__edit__menu.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/string-not_translatable.xml
  app/src/main/res/xml/preferences_master.xml
  doc/assets/2023-10-07-orgmode.webp
Labels: feature

#2119 Side margin improvements
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/res/values/dimens.xml
Labels: invalid/duplicate/upstream

#2124 Craft new overview for new formats OrgMode, AsciiDoc & Line number features
  NEWS.md
  doc/assets/2023-10-07-orgmode.webp
  doc/assets/2023-10-11-asciidoc.webp
  doc/assets/2023-10-11-line-numbers.webp
Labels: enhancement, hacktoberfest

#2125 BUGFIX: Using the correct format for correct types
  app/src/main/java/net/gsantner/markor/frontend/AttachLinkOrFileDialog.java
Labels: enhancement

#2130 Formats: Treat any XML based mime-type as text
  app/src/main/java/net/gsantner/opoc/util/GsFileUtils.java
Labels: enhancement

#2132 Reworked attachments, nr3 - #2125 #2106 #2132
  app/src/main/java/net/gsantner/markor/frontend/AttachLinkOrFileDialog.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
Labels: hacktoberfest-accepted

#2131 Update mermaid to 10.3.1
  .github/workflows/build-android-project.yml
  CONTRIBUTORS.md
  app/thirdparty/assets/mermaid/mermaid.min.js
Labels: enhancement, hacktoberfest-accepted
