Repository gsantner/markor, pull requests merged in 2023-05, with the labels that each got.

#2037 Filebrowser: Fix file search ignorelist
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchEngine.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserFragment.java
Labels: bug

#2014 todo.txt: Better project/context management
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtActionButtons.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/frontend/textview/ListHandler.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/java/net/gsantner/opoc/util/GsCollectionUtils.java
Labels: enhancement

#2022 Support AsciiDoc View-Mode by TextConverter with asciidoctor.js
  app/src/main/java/net/gsantner/markor/format/asciidoc/AsciidocTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/textview/AutoTextFormatter.java
  app/src/main/res/raw/licenses_3rd_party.md
  app/thirdparty/assets/asciidoc/asciidoctor.css
  app/thirdparty/assets/asciidoc/asciidoctor.min.js
  app/thirdparty/assets/asciidoc/dark.css
Labels: feature

#2038 Bugfix: undo-redo history at new created files
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/frontend/textview/ListHandler.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/opoc/frontend/textview/TextViewUndoRedo.java
Labels: bug

#2041 FileSearch: Sort search results alphabetically, closes #1864
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchEngine.java
Labels: enhancement

#1988 Add new format: CSV - Preview text converter and Editor syntax highlighting #1987
  CONTRIBUTORS.md
  app/build.gradle
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/format/FormatRegistry.java
  app/src/main/java/net/gsantner/markor/format/csv/CsvConfig.java
  app/src/main/java/net/gsantner/markor/format/csv/CsvSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/format/csv/CsvTextConverter.java
  app/src/main/java/net/gsantner/markor/format/keyvalue/KeyValueTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java
  app/src/main/java/net/gsantner/markor/model/Document.java
  app/src/main/java/net/gsantner/opoc/format/GsTextUtils.java
  app/src/main/res/menu/document__edit__menu.xml
  app/src/main/res/raw/licenses_3rd_party.md
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/string-not_translatable.xml
  app/src/test/java/net/gsantner/markor/format/csv/Csv2MdTableTest.java
  app/src/test/java/net/gsantner/opoc/format/GsTextUtilsTest.java
  doc/CSV_README.md
  samples/sample.csv
Labels: feature
