Repository gsantner/markor, pull requests merged in 2023-12, with the labels that each got.

#2148 Attachment improvements / bugfix v4
  app/src/main/java/net/gsantner/markor/activity/DocumentActivity.java
  app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtActionButtons.java
  app/src/main/java/net/gsantner/markor/frontend/AttachLinkOrFileDialog.java
  app/src/main/java/net/gsantner/markor/frontend/SearchAndReplaceTextDialog.java
  app/src/main/java/net/gsantner/markor/frontend/textview/AutoTextFormatter.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/opoc/frontend/GsAudioRecordOmDialog.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
Labels: enhancement

#2129 Auto padding of code blocks
  CONTRIBUTORS.md
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/res/drawable/ic_line_numbers_24dp.xml
  app/src/main/res/raw/licenses_3rd_party.md
  app/thirdparty/assets/prism/Prism v1.29.0
  app/thirdparty/assets/prism/components/prism-batch.min.js
  app/thirdparty/assets/prism/components/prism-cmake.min.js
  app/thirdparty/assets/prism/components/prism-css.min.js
  app/thirdparty/assets/prism/components/prism-csv.min.js
  app/thirdparty/assets/prism/components/prism-dart.min.js
  app/thirdparty/assets/prism/components/prism-elixir.min.js
  app/thirdparty/assets/prism/components/prism-fortran.min.js
  app/thirdparty/assets/prism/components/prism-groovy.min.js
  app/thirdparty/assets/prism/components/prism-haskell.min.js
  app/thirdparty/assets/prism/components/prism-liquid.min.js
  app/thirdparty/assets/prism/components/prism-makefile.min.js
  app/thirdparty/assets/prism/components/prism-markdown.min.js
  app/thirdparty/assets/prism/components/prism-matlab.min.js
  app/thirdparty/assets/prism/components/prism-pascal.min.js
  app/thirdparty/assets/prism/components/prism-sql.min.js
  app/thirdparty/assets/prism/components/prism-visual-basic.js
  app/thirdparty/assets/prism/components/prism-xml-doc.min.js
  app/thirdparty/assets/prism/components/prism-yaml.min.js
  app/thirdparty/assets/prism/index.html
  app/thirdparty/assets/prism/main.js
  app/thirdparty/assets/prism/plugins/line-numbers/main.js
  app/thirdparty/assets/prism/plugins/line-numbers/prism-line-numbers.css
  app/thirdparty/assets/prism/plugins/line-numbers/style.css
  app/thirdparty/assets/prism/style.css
  app/thirdparty/assets/prism/version
  app/thirdparty/java/other/flexmark/ext/codeblocks/LineNumbersAttributeProvider.java
  app/thirdparty/java/other/flexmark/ext/codeblocks/LineNumbersExtension.java
  doc/assets/2023-10-11-line-numbers.webp
Labels: enhancement, hacktoberfest-accepted

#2128 Add Orgmode Preiview Support
  CONTRIBUTORS.md
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java
  app/src/main/res/drawable/ic_org_mode_file.xml
  app/src/main/res/menu/document__edit__menu.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/string-not_translatable.xml
  app/src/main/res/xml/preferences_master.xml
  app/thirdparty/assets/orgmode/org-bundle.js
  app/thirdparty/assets/orgmode/org.css
  doc/assets/2023-10-13-orgmode-preview.webp
  samples/orgmode-reference.org
Labels: feature, hacktoberfest, hacktoberfest-accepted

#2181 Material You Themed Icons Support
  app/src/main/res/drawable-anydpi-v26/ic_launcher.xml
  app/src/main/res/drawable/ic_launcher_monochrome.xml
Labels: feature
