Repository gsantner/markor, pull requests merged in 2024-10, with the labels that each got.

#2426 Add text case changing functionality (Fixes #2390)
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/util/TextCasingUtils.java
  app/src/main/res/drawable/ic_format_text_case_black_24dp.xml
  app/src/main/res/menu/document__edit__menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2438 Open .lrc extension as plaintext by default, closes #2322
  app/src/main/java/net/gsantner/markor/format/plaintext/PlaintextTextConverter.java
Labels: hacktoberfest, hacktoberfest-accepted

#2439 Register chess extension (.fen) for plaintext, closes #2241
  app/src/main/java/net/gsantner/markor/format/plaintext/PlaintextTextConverter.java
Labels: hacktoberfest, hacktoberfest-accepted

#2440 FileManager: Remove top submenu to open special folders, load storage overview in filemanager instead
  app/src/main/java/net/gsantner/markor/frontend/filebrowser/MarkorFileBrowserFactory.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserFragment.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserOptions.java
  app/src/main/res/menu/filesystem__menu.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/string-not_translatable.xml
Labels: hacktoberfest, hacktoberfest-accepted

#2445 Rework /storage mapped folders
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  build.gradle
Labels: hacktoberfest, hacktoberfest-accepted

#2449 Fix orgmode action buttons not being loaded
  app/src/main/java/net/gsantner/markor/activity/ActionButtonSettingsActivity.java
Labels: bug, hacktoberfest, hacktoberfest-accepted

#2450 orgmode: add more text styling syntax and buttons
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeActionButtons.java
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeSyntaxHighlighter.java
  app/src/main/res/values/string-not_translatable.xml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#2455 Override .org file extension to use text mimetype (*/* unrecognized on older devices)
  app/src/main/java/net/gsantner/opoc/util/GsFileUtils.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
