Repository gsantner/markor, pull requests merged in 2024-03, with the labels that each got.

#2206 Make headline dialog work in view mode
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/markor/format/TextConverterBase.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownActionButtons.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextActionButtons.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
Labels: feature

#2213 Enable fast scroll for file browser
  app/src/main/res/drawable/scrollbar_thumb.xml
  app/src/main/res/drawable/scrollbar_thumb_background.xml
  app/src/main/res/drawable/scrollbar_thumb_background_pressed.xml
  app/src/main/res/drawable/scrollbar_track.xml
  app/src/main/res/drawable/scrollbar_track_background.xml
  app/src/main/res/layout/opoc_filesystem_fragment.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#2238 Add action: 'duplicate lines'
  CONTRIBUTORS.md
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/res/drawable/ic_duplicate_lines_black_24dp.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/string-not_translatable.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2246 KaTex: Update to v0.16.10
  app/thirdparty/assets/katex/auto-render.min.js
  app/thirdparty/assets/katex/katex.min.css
  app/thirdparty/assets/katex/katex.min.js
  app/thirdparty/assets/katex/mhchem.min.js
Labels: bug, enhancement

#2248 Bundled fonts: Update Source Code Pro, closes #2184
  app/thirdparty/assets/fonts/Source Pro Code.ttf
Labels: enhancement

#2252 BinaryEmbed: Support AVIF image format image viewing
  app/src/main/java/net/gsantner/markor/format/binary/EmbedBinaryTextConverter.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
Labels: enhancement
