Repository gsantner/markor, pull requests merged in 2024-07, with the labels that each got.

#2307 Jump to correct heading via id, other tweaks, bugfixes
  app/src/main/java/net/gsantner/markor/activity/DocumentActivity.java
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/activity/DocumentShareIntoFragment.java
  app/src/main/java/net/gsantner/markor/activity/MainActivity.java
  app/src/main/java/net/gsantner/markor/activity/MarkorBaseActivity.java
  app/src/main/java/net/gsantner/markor/activity/SettingsActivity.java
  app/src/main/java/net/gsantner/markor/activity/StoragePermissionActivity.java
  app/src/main/java/net/gsantner/markor/activity/openeditor/OpenFromShortcutOrWidgetActivity.java
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/markor/format/FormatRegistry.java
  app/src/main/java/net/gsantner/markor/format/TextConverterBase.java
  app/src/main/java/net/gsantner/markor/format/asciidoc/AsciidocTextConverter.java
  app/src/main/java/net/gsantner/markor/format/binary/EmbedBinaryTextConverter.java
  app/src/main/java/net/gsantner/markor/format/csv/CsvTextConverter.java
  app/src/main/java/net/gsantner/markor/format/keyvalue/KeyValueTextConverter.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownActionButtons.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownSyntaxHighlighter.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/format/orgmode/OrgmodeTextConverter.java
  app/src/main/java/net/gsantner/markor/format/plaintext/PlaintextTextConverter.java
  app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtFilter.java
  app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtTask.java
  app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtTextConverter.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextActionButtons.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/AttachLinkOrFileDialog.java
  app/src/main/java/net/gsantner/markor/frontend/DatetimeFormatDialog.java
  app/src/main/java/net/gsantner/markor/frontend/FileInfoDialog.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java
  app/src/main/java/net/gsantner/markor/frontend/SearchAndReplaceTextDialog.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchDialog.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchResultSelectorDialog.java
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/markor/frontend/textview/TextViewUtils.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/markor/model/Document.java
  app/src/main/java/net/gsantner/markor/util/MarkorContextUtils.java
  app/src/main/java/net/gsantner/markor/web/MarkorWebViewClient.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  app/src/main/java/net/gsantner/opoc/util/GsCollectionUtils.java
  app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java
  app/src/main/java/net/gsantner/opoc/util/GsFileUtils.java
  app/src/main/res/drawable/empty_blank.xml
  app/src/main/res/drawable/rounded_corner_background.xml
  app/src/main/res/layout/document__activity.xml
  app/src/main/res/layout/opoc_filesystem_item.xml
  app/src/main/res/layout/widget_layout.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/prefactions_share_into.xml
  app/src/test/java/net/gsantner/markor/format/todotxt/TodoTxtFileRecognitionTests.java
  app/thirdparty/java/other/writeily/ui/WrConfirmDialog.java
  app/thirdparty/java/other/writeily/ui/WrRenameDialog.java
Labels: bug, enhancement

#2331 File browser: Make Folder and file icons visually better distinct (outlined icon for file), fixes #2186
  app/src/main/java/net/gsantner/markor/frontend/filebrowser/MarkorFileBrowserFactory.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserOptions.java
  app/src/main/res/drawable/ic_file_gray_24dp.xml
  app/src/main/res/drawable/ic_file_white_24dp.xml
  app/src/main/res/drawable/ic_folder_gray_24dp.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#2345 View-Mode: Prism codeblock copy to clipboard button, update Mermaid and dark mode, closes #2336 closes #2335
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/thirdparty/assets/flexmark/admonition.css
  app/thirdparty/assets/mermaid/mermaid.min.js
  app/thirdparty/assets/mermaid/version
  app/thirdparty/assets/prism/plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  app/thirdparty/assets/prism/plugins/line-numbers/style.css
  app/thirdparty/assets/prism/plugins/toolbar/prism-toolbar.css
  app/thirdparty/assets/prism/plugins/toolbar/prism-toolbar.min.js
  app/thirdparty/assets/prism/style.css
Labels: enhancement

#2351 Highlight the file when users back
  app/src/main/java/net/gsantner/markor/frontend/textview/HighlightingEditor.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
Labels: enhancement

#2355 Upgrade to Android SDK 35, AGP 8.5, Build tools 35, by @gsantner, closes #2346, closes #2305
  .github/workflows/build-android-project.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/flavorGplay/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/build.gradle
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/AndroidManifest.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#2359 Appearance improvements
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchDialog.java
  app/src/main/java/net/gsantner/markor/frontend/filesearch/FileSearchResultSelectorDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserDialog.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
  app/src/main/res/layout/expandable_list_group_item.xml
  app/src/main/res/layout/widget_layout.xml
  app/thirdparty/java/other/writeily/widget/WrMarkorWidgetProvider.java
Labels: enhancement

#2203 New Color picker, minsdk 16-18, closes #1428
  app/build.gradle
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/opoc/frontend/base/GsPreferenceFragmentBase.java
  app/src/main/res/xml/preferences_master.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/.gitignore
  app/thirdparty-lib-src/QuadFlask-colorpicker/LICENSE-QuadFlask.md
  app/thirdparty-lib-src/QuadFlask-colorpicker/README.md
  app/thirdparty-lib-src/QuadFlask-colorpicker/build.gradle
  app/thirdparty-lib-src/QuadFlask-colorpicker/proguard-rules.pro
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/androidTest/java/com/flask/colorpicker/ApplicationTest.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/AndroidManifest.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/CircleColorDrawable.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/ColorCircle.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/ColorPickerPreference.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/ColorPickerView.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/OnColorChangedListener.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/OnColorSelectedListener.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/Utils.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorPickerClickListener.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorPickerDialogBuilder.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/builder/ColorWheelRendererBuilder.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/builder/PaintBuilder.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/renderer/AbsColorWheelRenderer.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/renderer/ColorWheelRenderOption.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/renderer/ColorWheelRenderer.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/renderer/FlowerColorWheelRenderer.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/renderer/SimpleColorWheelRenderer.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/slider/AbsCustomSlider.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/slider/AlphaSlider.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/slider/LightnessSlider.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/java/com/flask/colorpicker/slider/OnValueChangedListener.java
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/layout/color_preview.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/layout/color_selector.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/layout/color_widget.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/layout/picker_edit.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/values/attrs.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/values/dimens.xml
  app/thirdparty-lib-src/QuadFlask-colorpicker/src/main/res/values/styles.xml
  app/thirdparty/java/other/com/flask/colorpicker/ColorPickerPreference.java
  settings.gradle
Labels: enhancement, feature

#2370 Various bugfixes (anchor/toc jumping, snippets folder, wikitext newfile, virtual directory browser)
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/markor/frontend/NewFileDialog.java
  app/src/main/java/net/gsantner/markor/model/AppSettings.java
  app/src/main/java/net/gsantner/opoc/frontend/filebrowser/GsFileBrowserListAdapter.java
Labels: bug

#2366 Add history scroll restoration for scroll views
  app/src/main/java/net/gsantner/markor/activity/DocumentEditAndViewFragment.java
  app/src/main/java/net/gsantner/markor/format/ActionButtonBase.java
  app/src/main/java/net/gsantner/markor/format/markdown/MarkdownTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/MarkorDialogFactory.java
  app/src/main/java/net/gsantner/opoc/frontend/GsHorizontalScrollView.java
  app/src/main/java/net/gsantner/opoc/frontend/GsSearchOrCustomTextDialog.java
  app/src/main/res/layout/document__fragment__edit.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/preferences_master.xml
Labels: enhancement

#2147 Fix conformance to Zim (and enable Insert Audio button): wrong attachment directories, linked file not found, missing image link's tags, minsdk 16-18
  CONTRIBUTORS.md
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextActionButtons.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextLinkResolver.java
  app/src/main/java/net/gsantner/markor/format/wikitext/WikitextTextConverter.java
  app/src/main/java/net/gsantner/markor/frontend/AttachLinkOrFileDialog.java
  app/src/test/java/net/gsantner/markor/format/wikitext/WikitextLinkResolverTests.java
Labels: bug, enhancement
